---
abstract: 'handle numerals in Unicode using the libuninum library'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  DDP: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicode-Number
requires:
  Alien::Uninum: 0
  XSLoader: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/zmughal/p5-Unicode-Number
  repository: https://github.com/zmughal/p5-Unicode-Number.git
version: 0.001
